SELECT J.AUTHOR_ID, J.AUTHOR_NAME, J.CATEGORY, SUM(J.PRICE * S.SALES) AS TOTAL_SALES
 FROM (
        SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, B.PRICE, A.AUTHOR_NAME
         FROM BOOK AS B
         JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
      ) AS J
 JOIN BOOK_SALES AS S ON J.BOOK_ID = S.BOOK_ID
 WHERE YEAR(S.SALES_DATE) = '2022' AND MONTH(S.SALES_DATE) = '1'
 GROUP BY J.AUTHOR_ID, J.CATEGORY
 ORDER BY J.AUTHOR_ID, J.CATEGORY DESC
; 
