# Write your MySQL query statement below
SELECT ID, SUM(CNT) AS NUM
 FROM ((SELECT REQUESTER_ID AS ID, COUNT(*) AS CNT
         FROM REQUESTACCEPTED
         GROUP BY REQUESTER_ID
        UNION ALL
        SELECT ACCEPTER_ID AS ID, COUNT(*) AS CNT
         FROM REQUESTACCEPTED
         GROUP BY ACCEPTER_ID)) T
 GROUP BY ID
 ORDER BY NUM DESC
 LIMIT 1
;