SELECT E.ID, IFNULL(J.CHILD_COUNT, 0) AS CHILD_COUNT
 FROM ECOLI_DATA AS E
 LEFT OUTER JOIN (
        SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
        FROM ECOLI_DATA
        GROUP BY PARENT_ID
      ) AS J ON E.ID = J.PARENT_ID
 ORDER BY ID
;