-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(PRICE * TOTAL) AS SALES
 FROM PRODUCT P
 JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL
        FROM OFFLINE_SALE
        GROUP BY PRODUCT_ID) J ON P.PRODUCT_ID = J.PRODUCT_ID
 GROUP BY PRODUCT_CODE
 ORDER BY SALES DESC, PRODUCT_CODE
;