-- 코드를 입력하세요
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
 FROM ONLINE_SALE
 WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '03'
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
 FROM OFFLINE_SALE
 WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '03' 
 ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
;