-- 코드를 입력하세요
WITH DIFF AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
     FROM CAR_RENTAL_COMPANY_CAR C
     WHERE NOT EXISTS (SELECT CAR_ID 
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
                        WHERE C.CAR_ID = RH.CAR_ID 
                            AND RH.END_DATE >= '2022-11-01' 
                            AND RH.START_DATE <= '2022-11-30')
           AND (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV')
)

SELECT D.CAR_ID, D.CAR_TYPE, D.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * 30 AS FEE
 FROM DIFF D
 JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON D.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
 WHERE D.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * 30 >= 500000 AND 
       D.DAILY_FEE * ((100 - P.DISCOUNT_RATE) / 100) * 30 < 2000000
 ORDER BY FEE DESC, D.CAR_TYPE, D.CAR_ID DESC
;