# Write your MySQL query statement below
SELECT ST.STUDENT_ID, ST.STUDENT_NAME, SJ.SUBJECT_NAME,
       (CASE WHEN EX.ATTENDED_EXAMS IS NULL THEN 0 ELSE EX.ATTENDED_EXAMS END) AS ATTENDED_EXAMS
 FROM STUDENTS ST
 CROSS JOIN SUBJECTS SJ 
 LEFT JOIN (SELECT STUDENT_ID, SUBJECT_NAME, COUNT(*) AS ATTENDED_EXAMS
        FROM EXAMINATIONS
        GROUP BY STUDENT_ID, SUBJECT_NAME) EX ON ST.STUDENT_ID = EX.STUDENT_ID AND SJ.SUBJECT_NAME = EX.SUBJECT_NAME
 ORDER BY ST.STUDENT_ID, SJ.SUBJECT_NAME
;