-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
 FROM REST_INFO R
 JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS BEST FROM REST_INFO GROUP BY FOOD_TYPE) J ON R.FOOD_TYPE = J.FOOD_TYPE
 WHERE R.FAVORITES = J.BEST
 GROUP BY R.FOOD_TYPE
 ORDER BY R.FOOD_TYPE DESC
;