SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
 FROM REST_INFO AS I
 JOIN (
         SELECT FOOD_TYPE, MAX(FAVORITES) AS BEST_FAVORITES
         FROM REST_INFO
         GROUP BY FOOD_TYPE
      ) AS F ON I.FOOD_TYPE = F.FOOD_TYPE
 WHERE I.FAVORITES = F.BEST_FAVORITES
 ORDER BY I.FOOD_TYPE DESC
;
