SELECT U.USER_ID, U.NICKNAME, 
       CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS '전체주소',
       CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS TLNO
 FROM USED_GOODS_USER AS U
 JOIN (
    SELECT WRITER_ID, COUNT(*) AS CNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    ) AS B ON U.USER_ID = B.WRITER_ID
 WHERE B.CNT >= 3
 ORDER BY U.USER_ID DESC
;