# Write your MySQL query statement below
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
 FROM (SELECT NAME, SALARY, DEPARTMENTID,
            DENSE_RANK() OVER (
                PARTITION BY DEPARTMENTID
                ORDER BY SALARY DESC
            ) AS RNK
        FROM EMPLOYEE) E
 JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
 WHERE E.RNK <= 3
;