SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
 FROM USER_INFO AS U
 JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID
 GROUP BY YEAR, MONTH, U.GENDER
 HAVING U.GENDER IS NOT NULL
 ORDER BY YEAR, MONTH, U.GENDER
;