-- 코드를 입력하세요
SELECT C.CAR_ID, IFNULL(AVAILABILITY, '대여 가능') AS AVAILABILITY
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
 LEFT JOIN (
        SELECT CAR_ID, '대여중' AS AVAILABILITY
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
      ) J ON C.CAR_ID = J.CAR_ID
 GROUP BY C.CAR_ID
 ORDER BY C.CAR_ID DESC
;