# Write your MySQL query statement below
SELECT S.PRODUCT_ID, S.YEAR AS FIRST_YEAR, S.QUANTITY, S.PRICE
 FROM SALES S
 JOIN (SELECT PRODUCT_ID, MIN(YEAR) AS MIN_YEAR
        FROM SALES
        GROUP BY PRODUCT_ID) J
 WHERE S.PRODUCT_ID = J.PRODUCT_ID AND S.YEAR = J.MIN_YEAR
;