# Write your MySQL query statement below
SELECT C.VISITED_ON, C.AMOUNT, ROUND(C.AMOUNT / 7, 2) AS AVERAGE_AMOUNT
 FROM (SELECT T.VISITED_ON, 
        SUM(AMOUNT) OVER (
            ORDER BY VISITED_ON
            ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
        ) AS AMOUNT,
        ROW_NUMBER() OVER (
            ORDER BY VISITED_ON
        ) AS RN
       FROM (SELECT VISITED_ON, SUM(AMOUNT) AS AMOUNT FROM CUSTOMER GROUP BY VISITED_ON) T
    ) C
 WHERE C.RN >= 7
 ORDER BY C.VISITED_ON
;