-- 코드를 입력하세요
SELECT HISTORY_ID, ((DATEDIFF(END_DATE, START_DATE) + 1) * (100 - IFNULL(DISCOUNT_RATE, 0)) * DAILY_FEE / 100) AS FEE
 FROM (SELECT (CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
                    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
              END) AS TYPE, CAR_TYPE, HISTORY_ID, DAILY_FEE, END_DATE, START_DATE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
        WHERE CAR_TYPE = '트럭') AS T
 LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = T.CAR_TYPE AND P.DURATION_TYPE = T.TYPE 
 ORDER BY FEE DESC, HISTORY_ID DESC
;
