SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
 FROM APPOINTMENT AS A
 JOIN PATIENT AS P ON P.PT_NO = A.PT_NO
 JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID
 WHERE YEAR(A.APNT_YMD) = 2022 AND MONTH(A.APNT_YMD) = 4 AND DAY(A.APNT_YMD) = 13
   AND A.APNT_CNCL_YN = 'N'
 ORDER BY A.APNT_YMD
;