SET @H = -1;
SELECT H.HOUR, IFNULL(J.COUNT, 0) AS COUNT
 FROM (SELECT @H := @H + 1 AS HOUR FROM ANIMAL_OUTS WHERE @H < 23) AS H
 LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS GROUP BY HOUR) AS J ON H.HOUR = J.HOUR
 ORDER BY H.HOUR
;