-- 코드를 입력하세요
SELECT HOUR, COUNT(DATETIME) AS COUNT
 FROM ANIMAL_OUTS AS A
 RIGHT JOIN (SELECT 0 AS HOUR
         FROM DUAL
         UNION ALL
        SELECT 1 FROM DUAL
         UNION ALL
        SELECT 2 FROM DUAL
         UNION ALL
        SELECT 3 FROM DUAL
         UNION ALL
        SELECT 4 FROM DUAL
         UNION ALL
        SELECT 5 FROM DUAL
         UNION ALL
        SELECT 6 FROM DUAL
         UNION ALL
        SELECT 7 FROM DUAL
         UNION ALL
        SELECT 8 FROM DUAL
         UNION ALL
        SELECT 9 FROM DUAL
         UNION ALL
        SELECT 10 FROM DUAL
         UNION ALL
        SELECT 11 FROM DUAL
         UNION ALL
        SELECT 12 FROM DUAL
         UNION ALL
        SELECT 13 FROM DUAL
         UNION ALL
        SELECT 14 FROM DUAL
         UNION ALL
        SELECT 15 FROM DUAL
         UNION ALL
        SELECT 16 FROM DUAL
         UNION ALL
        SELECT 17 FROM DUAL
         UNION ALL
        SELECT 18 FROM DUAL
         UNION ALL
        SELECT 19 FROM DUAL
         UNION ALL
        SELECT 20 FROM DUAL
         UNION ALL
        SELECT 21 FROM DUAL
         UNION ALL
        SELECT 22 FROM DUAL
         UNION ALL
        SELECT 23 FROM DUAL) J ON HOUR(DATETIME) = J.HOUR
 GROUP BY HOUR
 ORDER BY HOUR
;