SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
 FROM REST_REVIEW AS R
 JOIN MEMBER_PROFILE AS P ON R.MEMBER_ID = P.MEMBER_ID
 JOIN (
        SELECT MEMBER_ID, COUNT(MEMBER_ID) AS COUNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
      ) AS J ON R.MEMBER_ID = J.MEMBER_ID
 WHERE COUNT = (SELECT COUNT(MEMBER_ID) AS COUNT 
                FROM REST_REVIEW 
                GROUP BY MEMBER_ID 
                ORDER BY COUNT DESC 
                LIMIT 1)
 ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT
;