# Write your MySQL query statement below
SELECT PERSON_NAME
 FROM (SELECT PERSON_NAME, 
        SUM(WEIGHT) OVER (
            ORDER BY TURN
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS WEIGHT_SUM
        FROM QUEUE
        ORDER BY TURN) T
 WHERE WEIGHT_SUM <= 1000
 ORDER BY WEIGHT_SUM DESC
 LIMIT 1
;