-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, H.CAR_ID, COUNT(*) AS RECORDS
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
 LEFT JOIN (SELECT CAR_ID, COUNT(*) AS COUNT
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) IN (08, 09, 10)
            GROUP BY CAR_ID) J ON H.CAR_ID = J.CAR_ID
 WHERE J.COUNT >= 5 AND YEAR(START_DATE) = 2022 AND MONTH(START_DATE) IN (08, 09, 10)
 GROUP BY MONTH(START_DATE), H.CAR_ID
 ORDER BY MONTH(START_DATE), H.CAR_ID DESC
;