SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
 JOIN (
    SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
     WHERE YEAR(START_DATE) = 2022
       AND MONTH(START_DATE) BETWEEN 8 AND 10
     GROUP BY CAR_ID
     HAVING COUNT(*) >= 5
 ) AS H ON C.CAR_ID = H.CAR_ID
  WHERE YEAR(START_DATE) = 2022
   AND MONTH(START_DATE) BETWEEN 8 AND 10
 GROUP BY CAR_ID, MONTH(C.START_DATE)
 HAVING RECORDS > 0
 ORDER BY MONTH(C.START_DATE), C.CAR_ID DESC
;