SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (P.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
 FROM ECOLI_DATA AS E
 JOIN (
         SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
         FROM ECOLI_DATA
         GROUP BY YEAR(DIFFERENTIATION_DATE)
     ) AS P ON P.YEAR = YEAR(E.DIFFERENTIATION_DATE)
 ORDER BY YEAR(DIFFERENTIATION_DATE), (P.MAX_SIZE - E.SIZE_OF_COLONY) 
;