# Write your MySQL query statement below
WITH COUNT AS (
    SELECT T.REQUEST_AT, COUNT(*) AS TOTAL, SUM(CASE WHEN T.STATUS = 'completed' THEN 0 ELSE 1 END) AS CANCELLED
    FROM TRIPS T
    LEFT JOIN USERS U ON T.CLIENT_ID = U.USERS_ID
    LEFT JOIN USERS D ON T.DRIVER_ID = D.USERS_ID
    WHERE U.BANNED = 'No' AND D.BANNED = 'No'
    GROUP BY T.REQUEST_AT
)

SELECT REQUEST_AT AS Day, ROUND(CANCELLED / TOTAL, 2) AS 'Cancellation Rate'
 FROM COUNT
 WHERE REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
;