# Write your MySQL query statement below
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
 FROM EMPLOYEE E
 JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
 JOIN (SELECT DEPARTMENTID, MAX(SALARY) AS HIGHEST
        FROM EMPLOYEE
        GROUP BY DEPARTMENTID) J
 WHERE E.DEPARTMENTID = J.DEPARTMENTID AND E.SALARY = J.HIGHEST
;