# Write your MySQL query statement below
SELECT IFNULL(ROUND(COUNT(*) / TOTAL, 2), 0) AS FRACTION
 FROM (SELECT DISTINCT PLAYER_ID
        FROM ACTIVITY A
        WHERE A.EVENT_DATE = (SELECT MIN(EVENT_DATE) FROM ACTIVITY C WHERE A.PLAYER_ID = C.PLAYER_ID GROUP BY C.PLAYER_ID)
        AND EXISTS (SELECT * 
                       FROM ACTIVITY B
                       WHERE A.PLAYER_ID = B.PLAYER_ID
                       AND DATEDIFF(B.EVENT_DATE, A.EVENT_DATE) = 1)) T
 JOIN (SELECT COUNT(DISTINCT PLAYER_ID) AS TOTAL FROM ACTIVITY) J
;