SELECT SC.SCORE, SC.EMP_NO, EM.EMP_NAME, EM.POSITION, EM.EMAIL
 FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE 
     FROM HR_GRADE
     GROUP BY EMP_NO
     ORDER BY SCORE DESC
     LIMIT 1
 ) AS SC
 JOIN HR_EMPLOYEES AS EM ON EM.EMP_NO = SC.EMP_NO
;
 