# Write your MySQL query statement below
WITH TMP AS (
    SELECT ID, VISIT_DATE, PEOPLE,
        ROW_NUMBER() OVER (ORDER BY ID) AS RNK
    FROM STADIUM
    WHERE PEOPLE >= 100
), CNT AS (
    SELECT *,
        COUNT(*) OVER (PARTITION BY ID - RNK) AS COUNT
    FROM TMP
)

SELECT ID, VISIT_DATE, PEOPLE
FROM CNT
WHERE COUNT >= 3
ORDER BY VISIT_DATE
;