SELECT F.CATEGORY, PRICE, PRODUCT_NAME
 FROM FOOD_PRODUCT AS F
 JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
 ) AS J ON F.CATEGORY = J.CATEGORY
 WHERE F.CATEGORY IN ('과자', '국', '김치', '식용유')
 AND F.PRICE = J.MAX_PRICE
 ORDER BY PRICE DESC
;