# Write your MySQL query statement below
SELECT DISTINCT L.NUM AS CONSECUTIVENUMS
 FROM LOGS L
 LEFT JOIN LOGS J ON L.ID = J.ID + 1
 LEFT JOIN LOGS JJ ON J.ID = JJ.ID + 1
 WHERE L.NUM = J.NUM AND J.NUM = JJ.NUM
;